POST http://localhost:8080/person/add
Content-Type: application/json

{
  "firstName": "GGGGGG",
  "lastName": "LaLA",
  "birthday": "1997-03-03"
}

####
GET http://localhost:8080/person/list
#####
GET http://localhost:8080/person/byFirsName